on:
  workflow_call:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        version-args:
            required: true
            type: string
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          token: ${{ secrets.PAT }}
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10.23.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Run install
        run: pnpm install --frozen-lockfile

      - name: Set up github actions user
        run: |
          git config --global user.name "keiya01"
          git config --global user.email "34934510+keiya01@users.noreply.github.com"

      - name: Run npm version
        run: npm version ${{ inputs.version-args }}

      - name: Git push
        run: |
          git push origin ${{ inputs.branch }}
          git push --tags

      - name: Release to NPM
        uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ inputs.tag }}
