on:
  workflow_call:
    inputs:
        tag:
          required: true
          type: string
        version-args:
            required: true
            type: string
    secrets:
      npm-token:
        required: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "path=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run install
        run: yarn install --frozen-lockfile
      - name: Run npm version
        run: npm version --no-git-tag-version ${{ inputs.version-args }}

  publish:
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm-token }}
          tag: ${{ inputs.tag }}
          dry-run: true
