on:
  workflow_call:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        version-args:
            required: true
            type: string
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "path=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run install
        run: yarn install --frozen-lockfile

      - name: Set up github actions user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run npm version
        run: npm version ${{ inputs.version-args }}

      - name: Push tag
        run: git push --tags

      - name: Get new version
        id: npm
        run: echo "version=$(cat package.json| jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: Create pull request to bump version
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          branch: bump/version-${{ inputs.tag }}
          title: "chore: bump version to ${{ steps.npm.outputs.version }}"

      - name: Release to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ inputs.tag }}
