on:
  push:
    branches: alpha
    paths-ignore:
      - "package.json"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: reearth/core/.github/workflows/npm_release.yml@beta
    with:
      branch: alpha
      tag: alpha
      version-args: --preid alpha prerelease
    secrets:
      PAT: ${{ secrets.PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
