on:
  push:
    branches: beta
    paths-ignore:
      - "package.json"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: reearth/core/.github/workflows/npm_release.yml@b70d597c18e8346abd10066dfb3f7addd9ed1af3 # beta
    with:
      branch: beta
      tag: beta
      version-args: --preid beta prerelease
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT: ${{ secrets.PAT }}
