on:
  push:
    branches: feat/release-flow

jobs:
  release:
    uses: reearth/core/.github/workflows/npm_release.yml@feat/release-flow
    with:
        tag: beta
        version-args: --preid beta prerelease
