on:
  workflow_dispatch:
    inputs:
      version-type:
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    permissions:
      contents: write
    uses: reearth/core/.github/workflows/npm_release.yml@b70d597c18e8346abd10066dfb3f7addd9ed1af3 # beta
    with:
      branch: main
      tag: latest
      version-args: ${{ inputs.version-type }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT: ${{ secrets.PAT }}
