on:
  push:
    branches: ci/pull-request

jobs:
  release:
    uses: reearth/core/.github/workflows/npm_release.yml@ci/pull-request
    with:
        branch: ci/pull-request
        tag: beta
        version-args: --preid beta prerelease
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT: ${{ secrets.PAT }}
