on:
  push:
    branches: alpha

jobs:
  release:
    uses: reearth/core/.github/workflows/npm_release.yml@main
    with:
        branch: alpha
        tag: alpha
        version-args: --preid alpha prerelease
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
